# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/xiaohangsu
  LinkedIn: https://www.linkedin.com/in/xiaohangsu
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-97026578-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
